- name: Update ECS task definition
  id: update-task-def
  run: |
    IMAGE="${{ secrets.DOCKER_USERNAME }}/medusa-store:latest"

    TASK_DEF=$(aws ecs describe-task-definition \
      --task-definition medusa-task \
      --region us-east-1)

    NEW_TASK_DEF=$(echo "$TASK_DEF" | jq \
      --arg IMAGE "$IMAGE" \
      '.taskDefinition |
      .containerDefinitions[0].image = $IMAGE |
      del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)')

    NEW_TASK_DEF_ARN=$(aws ecs register-task-definition \
      --region us-east-1 \
      --cli-input-json "$NEW_TASK_DEF" \
      | jq -r '.taskDefinition.taskDefinitionArn')

    echo "task_definition_arn=$NEW_TASK_DEF_ARN" >> $GITHUB_OUTPUT

- name: Update ECS service
  run: |
    aws ecs update-service \
      --cluster medusa-cluster \
      --service medusa-service \
      --task-definition ${{ steps.update-task-def.outputs.task_definition_arn }} \
      --force-new-deployment \
      --region us-east-1

- name: Wait for ECS service to stabilize
  run: |
    aws ecs wait services-stable \
      --cluster medusa-cluster \
      --services medusa-service \
      --region us-east-1
